### PR TITLE
feat: Added site custom domains page | Updated domain model and admin |  #4199

### LINKED ISSUE #4199: Update domain model to be associated to a site branch config
Update the domain model to be associated with a site branch config.

## Acceptance Criteria

- [x] Add one to many association between site_branch_config and domain.
- [x] Add `siteBranchConfigId` as a foreign key on the domain table
- [x] Add migration to insert `siteBranchConfigId` to domain records based on the domain's site id and context columns to query the related site_branch_config record.
- [ ] Update Admin UI to create new custom domains by site branch config.
- [ ] Add default 404.html to CDN service launch

### PR DESCRIPTION
**Pull request by apburnes**
Closes #4199

## Changes proposed in this pull request:
- Updated domain model to not require context column
- Updated domain model to associate a site branch config to a domain
- Added migration to domains to associate site branch config
- Updated "Custom Domains" page for customers to see their domain status, context, branch, and urls
- Updated admin UI to select related site branch configs on new domain create 
- Updated admin api routes for domains to simplify domain create and provisioning
- Updated site branch builds to check for a custom, provisioned domain

## security considerations
None

## UI Updates

Custom Domains Page
Screenshot 2023-08-09 at 11 02 58 AM

Admin - Create Domain Page
Screenshot Admin - Create Domain Page

### CODE REVIEW

**Review by drewbo — COMMENTED** [review]
GUI thoughts before looking too much through code:
- User-facing portion: can we disable the Github link for preview branches? Because it's null it will always be a dead link; probably a similar thought for preview domain since that link is path dependent
- Admin:
  - How is the branch/context list populated when adding a new domain?
  - Are we able to show all associated domains now in the site view? (this can be a separate PR/issue, just wondering if it's possible since some are still empty with associated domains)

**Comment by apburnes** [comment]
User Facing:
- A branch will never be null for a domain. This was a dev seeding error and I updated this PR to reflect that. We can keep, remove, or update the branch link.
- We can setup logic for the domains list to link or not based on the state of the domain.

Admin
- You can filter domains by site in the domain list view
- The branch/context list is populated by the site's associated site branch configs that are not with the context "preview" since "preview" context has no specific branch. Currently, the users' "Site settings" page allows them to add/edit "site", "demo", and "preview" configs but we can add functionality to customize their own branch configurations.

**Review by drewbo — APPROVED** [review]
Looks good to me pending any action you want to take regarding non-provisioned domain links. I'd also update the commit to `feat` since this involves user-facing changes in the new domain tab

**Comment by apburnes** [comment]
Thanks @drewbo. I'm going to clean up the user's custom domains and then rebase with the `feat` tag. I throw in a screenshot of the update.

**Review by drewbo — APPROVED** [review]

**Pull request merged**
