### PR TITLE
Feature: move site deletion to a background job

### LINKED ISSUE #4047: Move the site deletion process into a queued job
When a user is deleting a site, the UI should be responsive and the delete action should be successful. Currently, the delete action happens during the request to the API, so the user will experience a long loading screen while the site deletes and if request gets interrupted, the sites infrastructure may not be properly deleted.

## Acceptance Criteria

- [x] Update the API endpoint to soft delete the site's record in the database and kick off the job to delete its infrastructure
- [x] Update the [`./api/services/SiteDestroyer` service](https://github.com/cloud-gov/pages-core/blob/staging/api/services/SiteDestroyer.js) to be able to be run as background job
- [x] Add the job to the [`api/workers` directory](https://github.com/cloud-gov/pages-core/tree/staging/api/workers)

### PR DESCRIPTION
**Pull request by drewbo**
## Changes proposed in this pull request:
- Close #4047 
- I partially updated the test (to the point that they are passing) but I'd be open to feedback that they need improving, or we can wait for a larger test refactor

## security considerations
None

### CODE REVIEW

**Comment by svenaas** [comment]
Any testing advice on this, @drewbo?

**Comment by drewbo** [comment]
@svenaas it's unlikely to work locally since we don't stand up a local S3 stack so right now it's:
- unit tests + 
- test once it's on staging

**Comment by svenaas** [comment]
That's what I expected. 

I'm getting a unit test failure locally but I don't think it's related to this; I might have missed a setup step. But for what it's worth:
```
<AdvancedSiteSettingsForm/>
       should render:

      AssertionError: expected ShallowWrapper{ length: 4, …(8) } to have a length of 2 but got 4
      + expected - actual

      -4
      +2
      
      at Context.<anonymous> (test/frontend/components/site/SiteSettings/AdvancedSiteSettingsForm.test.jsx:30:43)
      at processImmediate (node:internal/timers:471:21)
```

**Comment by svenaas** [comment]
Obviously that's not happening in CI.

**Comment by svenaas** [comment]
I rebuilt in Docker and am still getting that failure, though I fail to see the connection.

**Review by svenaas — DISMISSED** [review]
I am on the fence about commenting out the tests instead of removing them, but it's not hurting anything and it's a more convenient reference.

This looks ready for testing on staging.

**Comment by drewbo** [comment]
@svenaas I have a vague recollection of introducing that test error in the #4030 PRs and confirm that it (1) occurs for me running locally (2) but not on CI and (3) most confusingly, it doesn't occur when running that single test file on it's own. So that can remain a mystery for now.

I've updated and restored the commented out tests for better coverage

**Review by svenaas — APPROVED** [review]
Approved.

**Pull request merged**
