### PR TITLE
Update production domain services to point CDN origin to the pages proxy

### PR DESCRIPTION
**Pull request by svenaas**
Work towards #4015

Adds `scripts/update-cdn-origins.sh` which works through an input CSV containing `id,serviceName,origin` tuples, calling `cf update-service` to update the CDN origin from Federalist to cloud.gov Pages standard, and emits the SQL which needs to be run in the DB to make the corresponding change against the `domains` table.

## Changes proposed in this pull request:
- Adds `scripts/update-cdn-origins.sh`

## security considerations
None. No changes are introduced into the running codebase. This is a script for use by administrators under specific circumstances.

### CODE REVIEW

**Comment by svenaas** [comment]
Force-pushed because I had branched from `main` instead of `staging` and I rebased this branch to fix that.

**Comment by svenaas** [comment]
Moving this work over to cg-scripts as cloud-gov/cg-scripts#237

**Comment by svenaas** [comment]
Waking this version back up because of jumpbox-related challenges.

**Comment by svenaas** [comment]
Ready for review

**Review by apburnes — APPROVED** [review]

**Comment by svenaas** [comment]
@drewbo I just removed a couple of embarrassing lingering debug lines. Could you please review so I can merge and close out this branch?

**Comment by svenaas** [comment]
Could one of y'all please review this so I can get the code committed? This is the version that was run against production, and Andrew already approved it last week before I committed a minor fix and remerged staging.

**Review by apburnes — APPROVED** [review]
Thanks!

**Pull request merged**
